public with sharing class ImplementClassPosition1 extends abstractclass1 implements InteferfaceClassPosition1 {

public double avgpay()
{
	double a;
	return a=24.22;
}

public double recalc()
{
	double a;
	return a=24.22;
}

public double test1()
{
	double x;
	return x=11.11;
}

public string test2()
{

	string x;
	return x='hello';	
}

public override string a(){
	string x;
	x='haha called in implement class';
	return x;
}

}